<?php

namespace Payroll\AuthModule\Router;

use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

class Index extends \App\Data\Router{

	private static $name = "Payroll\AuthModule\Router\Index";

	public  $autoGenerated = true;

	/**
	* @Route(/)
	* @Method(GET, POST)
	* @Provides(application/json)
	* @Middleware(AuthToken)
	* @Middleware(GVerify)
	*/
	public function welcome(){

		//
	}

	/**
	* @Route(/hello/{to:alpha})
	* @Method(GET, POST)
	* @Provides(application/html)
	* @Middlewares(A, B, C)
	*/
	public function hello($to){

		//
	}

	/**
	* @Route(/login)
	* @Method(GET)
	* @Secure(username=admin, password=p@55w0rd)
	* @Expects(username, password)
	*/
	public function login($username, $password){

		//
	}
}